name: plato_calendar
description: calendar app using plato.
publish_to: 'none'


version: 4.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  icalendar_parser: ^2.1.0
  syncfusion_flutter_calendar: ^27.2.4   # calendar


  flutter_bloc: ^8.1.6  # bloc 디자인 패턴 적용
  logging: ^1.2.0       # logging 라이브러리

  equatable: ^2.0.0

  cupertino_icons: ^1.0.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
