// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaEhfHmrV8fXfClz3GP0jKqvOygkRUusk',
    appId: '1:530960691637:android:f9a224567e66568a24a9fc',
    messagingSenderId: '530960691637',
    projectId: 'plato-calendar',
    storageBucket: 'plato-calendar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHVrllxXf-ZPYW3Yl58DDjg7tLgvzIc1U',
    appId: '1:530960691637:ios:7db6be397c29001f24a9fc',
    messagingSenderId: '530960691637',
    projectId: 'plato-calendar',
    storageBucket: 'plato-calendar.appspot.com',
    androidClientId: '530960691637-18bfv265ou24630kftgb44dtfgsii0jl.apps.googleusercontent.com',
    iosClientId: '530960691637-b5u0rhsr9mgrcue6trlm9e666p63vc8v.apps.googleusercontent.com',
    iosBundleId: 'com.seunggil.platoCalendar',
  );
}
