name: plato_calendar
description: calendar app using plato.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.3.2+202304172

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 달력
  icalendar_parser: ^1.0.1
  syncfusion_flutter_calendar: ^20.4.50
  
  # network
  http: ^0.13.3
  html: ^0.15.0
  dio: ^5.0.0
  connectivity_plus: ^3.0.3

  # 폰트 동적 사이즈 조절
  auto_size_text: ^3.0.0
  # DateFormat("MM-dd HH:mm:ss").format(data),
  intl: ^0.18.0
  flutter_datetime_picker: ^1.5.0

  # toast 메세지, 알림 메세지
  fluttertoast: ^8.0.8
  flutter_local_notifications: ^13.0.0

  # database
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  # path_provider: ^2.0.8
  flutter_secure_storage: ^8.0.0

  # open_file: ^3.2.1
  
  # google ad
  google_mobile_ads:

  # google calendar api
  googleapis: ^10.1.0
  googleapis_auth: ^1.1.0
  flutter_signin_button: ^2.0.0
  
  url_launcher: ^6.0.9

  # firebase
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0

  # logging
  device_info_plus: ^8.0.0
  mailer: ^6.0.0
  # android uuid 얻기가 막힘에 따라 guid 생성 패키지 사용
  flutter_guid : ^0.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.1.7
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  # assets:
      #- icalexport.ics

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
