name: Flutter CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: |
          flutter analyze || true
          flutter analyze | findstr /v "info" | findstr /v "warning" # Windows용 findstr 사용

      - name: Run tests
        run: flutter test
